apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dlf
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
        - name: RABBITMQ_QUEUE_NAME
          value: nginx-queue
        - name: RABBITMQ_URI
          value: amqps://admin:<password>@b-264600ed.mq.us-east-1.amazonaws.com:5671
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app.kubernetes.io/name: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9333
